{% set version = "1.2.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-shapes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shapes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shapes/shapes_{{ version }}.tar.gz
  sha256: 2b1df1abbe8f4836e20bb23844fabe8acb3f7ca09b9fc9fbe9cd55d972463333

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip                 # [win]
    - cross-r-base {{ r_base }}      # [build_platform != target_platform]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxfixes') }}         # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
  host:
    - r-base
    - r-mass
    - r-fitdistrplus
    - r-minpack.lm
    - r-rgl
    - r-scatterplot3d
  run:
    - r-base
    - r-mass
    - r-fitdistrplus
    - r-minpack.lm
    - r-rgl
    - r-scatterplot3d

test:
  commands:
    - LD_LIBRARY_PATH="${BUILD_PREFIX}/x86_64-conda-linux-gnu/sysroot/usr/lib64:${BUILD_PREFIX}/lib" $R -e "library('shapes')"  # [not win]
    - "\"%R%\" -e \"library('shapes')\""  # [win]

about:
  home: http://www.maths.nottingham.ac.uk/~ild/shapes
  license: GPL-2.0-only
  summary: Routines for the statistical analysis of landmark shapes, including Procrustes analysis, graphical displays, principal components analysis, permutation and bootstrap tests, thin-plate spline transformation grids and comparing covariance matrices. See Dryden, I.L. and Mardia, K.V. (2016). Statistical shape analysis,
    with Applications in R (2nd Edition), John Wiley and Sons.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
